name: Test Action

on:
  workflow_dispatch:
    inputs:
      command:
        description: "command"
        required: true
        default: "pwd"

jobs:
  Compile:
    runs-on: ubuntu-20.04

    steps:
      - name: Command
        run: |
          echo "${{ github.event.inputs.command }}"
